spring:
  application:
    name: poker-
  datasource:
    url: jdbc:mysql://localhost:3306/poker_online?useSSL=false&serverTimezone=UTC
    username: root
    password: seasame # Đổi thành password MySQL của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50 # Xử lý 50 luồng kết nối DB cùng lúc
      minimum-idle: 10
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # Tự động đồng bộ Entity Java với MySQL
    show-sql: true # In câu lệnh SQL ra console
    properties:
      hibernate:
        format_sql: true
